"""Add plan_ids to Puja model

Revision ID: 0c870091295e
Revises: b430ed464443
Create Date: 2025-10-17 23:45:15.277526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c870091295e'
down_revision = 'b430ed464443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
