"""Update PujaBenefit with title and description fields

Revision ID: 26dbae314f45
Revises: 361445d073f4
Create Date: 2025-10-02 11:07:30.570581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dbae314f45'
down_revision = '361445d073f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puja_benefits', sa.Column('benefit_title', sa.String(length=200), nullable=False))
    op.add_column('puja_benefits', sa.Column('benefit_description', sa.Text(), nullable=False))
    op.drop_column('puja_benefits', 'benefit_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puja_benefits', sa.Column('benefit_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('puja_benefits', 'benefit_description')
    op.drop_column('puja_benefits', 'benefit_title')
    # ### end Alembic commands ###
