"""Update Puja model with new fields and PujaBenefit

Revision ID: 361445d073f4
Revises: 0462c710fc07
Create Date: 2025-10-02 11:02:39.944054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361445d073f4'
down_revision = '0462c710fc07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pujas', sa.Column('sub_heading', sa.String(length=255), nullable=False))
    op.add_column('pujas', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('pujas', sa.Column('time', sa.Time(), nullable=True))
    op.add_column('pujas', sa.Column('temple_image_url', sa.String(length=500), nullable=True))
    op.add_column('pujas', sa.Column('temple_address', sa.Text(), nullable=True))
    op.add_column('pujas', sa.Column('temple_description', sa.Text(), nullable=True))
    op.add_column('pujas', sa.Column('prasad_price', sa.Integer(), nullable=True))
    op.add_column('pujas', sa.Column('is_prasad_active', sa.Boolean(), nullable=True))
    op.add_column('pujas', sa.Column('dakshina_prices_inr', sa.String(), nullable=True))
    op.add_column('pujas', sa.Column('dakshina_prices_usd', sa.String(), nullable=True))
    op.add_column('pujas', sa.Column('is_dakshina_active', sa.Boolean(), nullable=True))
    op.add_column('pujas', sa.Column('manokamna_prices_inr', sa.String(), nullable=True))
    op.add_column('pujas', sa.Column('manokamna_prices_usd', sa.String(), nullable=True))
    op.add_column('pujas', sa.Column('is_manokamna_active', sa.Boolean(), nullable=True))
    op.add_column('pujas', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pujas', 'category')
    op.drop_column('pujas', 'is_manokamna_active')
    op.drop_column('pujas', 'manokamna_prices_usd')
    op.drop_column('pujas', 'manokamna_prices_inr')
    op.drop_column('pujas', 'is_dakshina_active')
    op.drop_column('pujas', 'dakshina_prices_usd')
    op.drop_column('pujas', 'dakshina_prices_inr')
    op.drop_column('pujas', 'is_prasad_active')
    op.drop_column('pujas', 'prasad_price')
    op.drop_column('pujas', 'temple_description')
    op.drop_column('pujas', 'temple_address')
    op.drop_column('pujas', 'temple_image_url')
    op.drop_column('pujas', 'time')
    op.drop_column('pujas', 'date')
    op.drop_column('pujas', 'sub_heading')
    # ### end Alembic commands ###
