"""Add multiple category in blog

Revision ID: 368b97d4deee
Revises: 1a549ba896c9
Create Date: 2025-10-18 00:53:00.695413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368b97d4deee'
down_revision = '1a549ba896c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blogs_category_id_fkey'), 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('blogs_category_id_fkey'), 'blogs', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
