"""add_cascade_delete_on_puja_images

Revision ID: 4a8839b6075a
Revises: 8975fb1b4479
Create Date: 2025-10-10 23:04:54.628329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8839b6075a'
down_revision = '8975fb1b4479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('puja_images_puja_id_fkey'), 'puja_images', type_='foreignkey')
    op.create_foreign_key(None, 'puja_images', 'pujas', ['puja_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puja_images', type_='foreignkey')
    op.create_foreign_key(op.f('puja_images_puja_id_fkey'), 'puja_images', 'pujas', ['puja_id'], ['id'])
    # ### end Alembic commands ###
