"""add booking in the temple

Revision ID: 61c976db42a6
Revises: add_temple_association_tables
Create Date: 2025-10-29 22:33:22.373893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c976db42a6'
down_revision = 'add_temple_association_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('temple_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'temple', ['temple_id'], ['id'])
    op.create_index(op.f('ix_temple_id'), 'temple', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temple_id'), table_name='temple')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'temple_id')
    # ### end Alembic commands ###
