"""Add puja_id to Plan model

Revision ID: 838a2a70b542
Revises: 0c870091295e
Create Date: 2025-10-18 00:10:10.033126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838a2a70b542'
down_revision = '0c870091295e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
