"""add_thumbnail_image_to_blogs

Revision ID: 8975fb1b4479
Revises: d4214c5e9914
Create Date: 2025-10-08 22:49:34.618040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8975fb1b4479'
down_revision = 'd4214c5e9914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('thumbnail_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'thumbnail_image')
    # ### end Alembic commands ###
