"""add_payment_methods_to_product_and_order

Revision ID: af96049e7c18
Revises: c234227948c0
Create Date: 2025-11-19 22:22:09.133299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af96049e7c18'
down_revision = 'c234227948c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add allow_cod column with default False for existing products
    op.add_column('products', sa.Column('allow_cod', sa.Boolean(), nullable=False, server_default='false'))
    
    # For orders table, we need to handle existing rows differently
    # First add as nullable
    op.add_column('orders', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # Update existing rows to have a default value
    op.execute("UPDATE orders SET payment_method = 'online' WHERE payment_method IS NULL")
    # Now make it non-nullable
    op.alter_column('orders', 'payment_method', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'allow_cod')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
