"""fix_puja_benefits_cascade_delete

Revision ID: b430ed464443
Revises: 4a8839b6075a
Create Date: 2025-10-11 01:29:17.953659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b430ed464443'
down_revision = '4a8839b6075a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('puja_benefits_puja_id_fkey'), 'puja_benefits', type_='foreignkey')
    op.create_foreign_key(None, 'puja_benefits', 'pujas', ['puja_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puja_benefits', type_='foreignkey')
    op.create_foreign_key(op.f('puja_benefits_puja_id_fkey'), 'puja_benefits', 'pujas', ['puja_id'], ['id'])
    # ### end Alembic commands ###
