"""add is_active to puja

Revision ID: b4d7cf5cc27d
Revises: 61c976db42a6
Create Date: 2025-10-30 22:48:53.302799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d7cf5cc27d'
down_revision = '61c976db42a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default so existing rows get a value and NOT NULL can be applied safely
    op.add_column('pujas', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pujas', 'is_active')
    # ### end Alembic commands ###
