"""add_blog_and_category_models

Revision ID: d4214c5e9914
Revises: 26dbae314f45
Create Date: 2025-10-08 22:31:22.960218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4214c5e9914'
down_revision = '26dbae314f45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
